title: JS30 Demos
author: Hunter Stevens
description: Demos for the JavaScript30 course by Wes Bos
theme: minima
twitter_username: twobree
github_username: onebree
exclude:
  - Gemfile
  - Gemfile.log

